### ISSUE TITLE
How to use replace multi file?

### ISSUE THREAD

**Issue by wushufen** [cvgellhorn/path-replace-loader#1]

**Comment by cvgellhorn** [comment]
Hey @wusfen,

could you elaborate a little further, I don't really get your question? 

The loader should replace every imported file from **path** with every matching available file from **replacePath** including all existing sub directories.


Cheers 
Chris

**Comment by wushufen** [comment]
Thank you.

I mean:
  if some files, they are not in same dir, how to replace them.

But now my way is:
```javascript
{
    loader: 'path-replace-loader',
    options: {
      path: 'a',
      replacePath: 'new.a',
    }
  },
 {
    loader: 'path-replace-loader',
    options: {
      path: 'b',
      replacePath: 'new.b',
    }
  }
```

I think `options` should support a list `options.list: [{},{}]`.

**Comment by cvgellhorn** [comment]
Good point, I will add support for lists if I find the time.

I would also like to update the loader in general for the current webpack version.

Hopefully all soonish...


Cheers 
Chris
